FSD50K = data/audios/fsd50k.zip
MUSDB18 = data/audios/musb18.zip

OUTPUT_DIR_FSDK50K = data/processed_fsd50k/
OUTPUT_DIR_MUSDB18 = data/processed_musb18/

LOG_DIR = logs/

WINRAR_PATH = "C:/Program Files/WinRAR/WinRAR.exe"
BRAVE_BROWSER_PATH = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"

